name: Master Build
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    - uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm 
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    
    - run: npm ci
    - run: npm run build
    - run: npm run test
    
    - name: Deploy the demo to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: dist
    
    - name: Archive source code
      uses: actions/upload-artifact@v2
      with:
        name: src
        path: dist-zip/src.zip

    - name: Archive build files
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist-zip/dist.zip
